public class AccountWrapper {
@AuraEnabled
    public String accName;
    @AuraEnabled
    public Boolean isActive;
    @AuraEnabled
    public String accIndustry;
    @AuraEnabled
    public String accType;
    @AuraEnabled
    public String accActive;   
    @AuraEnabled
    public String accId; 
     @AuraEnabled
    public Decimal annualRevenue; 
    @AuraEnabled
    public String Phone; 
    @AuraEnabled
    public String AccountType;
    
}